project:
  type: website
  output-dir: docs

# Meta
description-meta: "Andreas Laffert – Sociologist and M.A. in Sociology"
author-meta: "Andreas Laffert"

website:
  title: "Andreas Laffert"
  image: "/files/andreas_laffert.jpeg"
  description: "Andreas Laffert – Sociologist and M.A. in Sociology"
 
  navbar:
    background: dark

    left:
#      - text: Home
#        href: index.qmd
#      - text: About
#        menu:
#          - text: News
#            href: posts.qmd#category=news
#          - text: Events
#            href: posts.qmd#category=event
#          - text: Now
#            href: now.qmd       
#          - text: Contact
#            href: contact.qmd    
      - text: Research
        menu:
          - text: Projects
            href: projects.qmd
          - text: Publications
            href: publications.qmd
          - text: Presentations
            href: presentations.qmd  
            target: _blank                                  
      - text: Teaching
        href: teaching.qmd
      - text: Community Engagement
        href: community.qmd 

    right: 
      - text: "**CV**"
        href: files/cv-2-column.pdf
        target: _blank 
      - icon: github
        href: https://github.com/Andreas-Lafferte
        target: _blank
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=9zzyCGAAAAAJ&hl=es&oi=sra
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    center: "[Andreas Laffert](https://andreas-lafferte.github.io) &copy; <script>document.write(new Date().getFullYear())</script>"
    # left: "[Andreas Laffert](https://andreas-lafferte.github.io); <script>document.write(new Date().getFullYear())</script>" 
    right:  
       - icon: github
         href: https://github.com/Andreas-Lafferte
         target: _blank
    #   - text: "{{< fa brands bluesky >}}" 
    #     href: https://bsky.app/profile/hegang.bsky.social
    #     target: _blank
    #   - icon: rss
    #     href: posts.xml
    #     target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: false

  draft-mode: unlinked
  
  repo-url: https://github.com/Andreas-Lafferte/andreas-lafferte.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://andreas-lafferte.github.io"


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

